# Uncomment the next line to define a global platform for your project
platform :ios, ‘9.0’

target ‘BCObjCExam’ do
  # Uncomment the next line if you’re using Swift or would like to use dynamic frameworks
  use_frameworks!

 # Pods for BCObjCExam
  pod ‘BeastComponents’, :git => “https://github.com/istsest/BeastComponents.git”
end